name: Daily License Parser

on:
  schedule:
    # Запуск каждый день в 18:30 UTC (21:30 МСК)
    - cron: '30 18 * * *'
  
  workflow_dispatch:  # Позволяет запускать вручную
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable debug mode'
        required: false
        default: false

jobs:
  parse-licenses:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Display Chrome version
      run: |
        google-chrome --version
        which google-chrome
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
    
    - name: Run parser
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GITHUB_ACTIONS: true
      run: |
        echo "Starting parser at $(date)"
        python parser.py
        echo "Parser completed at $(date)"
    
    - name: Upload logs (if any)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: parser-logs
        path: |
          *.log
          *.txt
